#!/usr/bin/env node
/**
 * Generate TypeScript module from PayIn documentation
 *
 * This script reads all .md files from apps/docs/en/ directory and generates
 * a TypeScript module with embedded documentation content for MCP Server.
 *
 * Usage:
 *   node scripts/generate-docs.js
 *   npm run generate:docs
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Paths
const PROJECT_ROOT = path.resolve(__dirname, '../../..');
const DOCS_DIR = path.join(PROJECT_ROOT, 'apps/docs/en');
const OUTPUT_FILE = path.join(__dirname, '../src/generated/docs-content.ts');

console.log('📚 PayIn Documentation Generator\n');
console.log(`📁 Docs directory: ${DOCS_DIR}`);
console.log(`📄 Output file: ${OUTPUT_FILE}\n`);

/**
 * Read all markdown files from docs directory recursively
 */
function readDocs() {
  const docs = {};
  const meta = {};

  function readDir(dir, prefix = '') {
    if (!fs.existsSync(dir)) {
      console.error(`❌ Directory not found: ${dir}`);
      return;
    }

    const files = fs.readdirSync(dir);

    for (const file of files) {
      const filePath = path.join(dir, file);
      const stat = fs.statSync(filePath);

      if (stat.isDirectory()) {
        // Skip node_modules and hidden directories
        if (file.startsWith('.') || file === 'node_modules') {
          continue;
        }
        readDir(filePath, `${prefix}${file}/`);
      } else if (file.endsWith('.md')) {
        const key = `${prefix}${file.replace('.md', '')}`;
        const content = fs.readFileSync(filePath, 'utf-8');

        // Extract frontmatter metadata if exists
        const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---\n/);
        let metadata = {
          title: key,
          category: prefix.split('/')[0] || 'general',
          size: content.length
        };

        if (frontmatterMatch) {
          const frontmatter = frontmatterMatch[1];
          const titleMatch = frontmatter.match(/^title:\s*(.+)$/m);
          const categoryMatch = frontmatter.match(/^category:\s*(.+)$/m);
          const tagsMatch = frontmatter.match(/^tags:\s*\[(.+)\]$/m);

          if (titleMatch) metadata.title = titleMatch[1].trim();
          if (categoryMatch) metadata.category = categoryMatch[1].trim();
          if (tagsMatch) metadata.tags = tagsMatch[1].split(',').map(t => t.trim());
        }

        docs[key] = content;
        meta[key] = metadata;

        const sizeKB = (content.length / 1024).toFixed(2);
        console.log(`  ✓ ${key} (${sizeKB} KB)`);
      }
    }
  }

  console.log('📖 Reading documentation files...\n');
  readDir(DOCS_DIR);

  return { docs, meta };
}

/**
 * Escape string for TypeScript template literal
 */
function escapeForTemplate(str) {
  return str
    .replace(/\\/g, '\\\\')    // Escape backslashes
    .replace(/`/g, '\\`')      // Escape backticks
    .replace(/\$/g, '\\$');    // Escape dollar signs
}

/**
 * Generate TypeScript module
 */
function generateModule(docs, meta) {
  const docEntries = Object.entries(docs).map(([key, content]) => {
    const escaped = escapeForTemplate(content);
    return `  '${key}': \`${escaped}\``;
  });

  const metaEntries = Object.entries(meta).map(([key, metadata]) => {
    return `  '${key}': ${JSON.stringify(metadata)}`;
  });

  return `/**
 * Auto-generated documentation content
 * DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-docs.js
 * Generated at: ${new Date().toISOString()}
 * Source: ${DOCS_DIR}
 *
 * Usage:
 *   import { getDoc, searchDocs } from './docs-content.js';
 *   const content = getDoc('guide/getting-started');
 *   const results = searchDocs('payment');
 */

/**
 * Documentation content map
 * Key: document path (e.g., 'guide/getting-started')
 * Value: full markdown content
 */
export const docsContent: Record<string, string> = {
${docEntries.join(',\n')}
};

/**
 * Documentation metadata
 * Contains title, category, tags, and size information
 */
export const docsMeta: Record<string, {
  title: string;
  category: string;
  size: number;
  tags?: string[];
}> = {
${metaEntries.join(',\n')}
};

/**
 * Document key type
 */
export type DocKey = keyof typeof docsContent;

/**
 * Get documentation content by key
 *
 * @param key - Document key (e.g., 'guide/getting-started')
 * @returns Document content or empty string if not found
 *
 * @example
 * const content = getDoc('guide/getting-started');
 * console.log(content);
 */
export function getDoc(key: DocKey): string {
  return docsContent[key] || '';
}

/**
 * List all available document keys
 *
 * @returns Array of document keys
 *
 * @example
 * const keys = listDocs();
 * console.log('Available docs:', keys);
 */
export function listDocs(): DocKey[] {
  return Object.keys(docsContent) as DocKey[];
}

/**
 * Search result
 */
export interface SearchResult {
  key: DocKey;
  title: string;
  category: string;
  excerpt: string;
  relevance: number;
}

/**
 * Search documentation by keyword
 *
 * @param keyword - Search keyword or phrase
 * @param options - Search options
 * @returns Array of search results sorted by relevance
 *
 * @example
 * const results = searchDocs('payment order', { maxResults: 5 });
 * results.forEach(r => {
 *   console.log(\`\${r.title} (relevance: \${r.relevance}%)\`);
 *   console.log(r.excerpt);
 * });
 */
export function searchDocs(
  keyword: string,
  options: {
    category?: string;
    maxResults?: number;
    contextLength?: number;
  } = {}
): SearchResult[] {
  const {
    category,
    maxResults = 10,
    contextLength = 200
  } = options;

  const results: SearchResult[] = [];
  const lowerKeyword = keyword.toLowerCase();
  const keywords = lowerKeyword.split(/\\s+/);

  for (const [key, content] of Object.entries(docsContent)) {
    const metadata = docsMeta[key];

    // Filter by category if specified
    if (category && metadata.category !== category) {
      continue;
    }

    const lowerContent = content.toLowerCase();
    const lowerTitle = metadata.title.toLowerCase();

    // Calculate relevance score
    let relevance = 0;

    // Title match is most important
    if (lowerTitle.includes(lowerKeyword)) {
      relevance += 100;
    }

    // Check individual keyword matches in title
    for (const kw of keywords) {
      if (lowerTitle.includes(kw)) {
        relevance += 50;
      }
    }

    // Content matches
    let matchCount = 0;
    let firstMatchIndex = -1;

    for (const kw of keywords) {
      const index = lowerContent.indexOf(kw);
      if (index !== -1) {
        matchCount++;
        if (firstMatchIndex === -1) {
          firstMatchIndex = index;
        }
      }
    }

    if (matchCount > 0) {
      relevance += matchCount * 10;

      // Extract excerpt around first match
      const start = Math.max(0, firstMatchIndex - contextLength / 2);
      const end = Math.min(content.length, firstMatchIndex + contextLength / 2);
      let excerpt = content.substring(start, end).trim();

      // Clean up excerpt
      excerpt = excerpt.replace(/^#+\\s+/gm, ''); // Remove markdown headers
      excerpt = excerpt.replace(/\\n+/g, ' ');     // Replace newlines with spaces
      excerpt = excerpt.substring(0, contextLength);

      if (start > 0) excerpt = '...' + excerpt;
      if (end < content.length) excerpt = excerpt + '...';

      results.push({
        key: key as DocKey,
        title: metadata.title,
        category: metadata.category,
        excerpt,
        relevance
      });
    }
  }

  // Sort by relevance
  results.sort((a, b) => b.relevance - a.relevance);

  // Limit results
  return results.slice(0, maxResults);
}

/**
 * Get documents by category
 *
 * @param category - Category name
 * @returns Array of document keys in the category
 *
 * @example
 * const guideDocs = getDocsByCategory('guide');
 * guideDocs.forEach(key => {
 *   console.log(getDoc(key));
 * });
 */
export function getDocsByCategory(category: string): DocKey[] {
  return Object.entries(docsMeta)
    .filter(([_, meta]) => meta.category === category)
    .map(([key, _]) => key as DocKey);
}

/**
 * Statistics about the documentation
 */
export const docsStats = {
  totalDocs: ${Object.keys(docs).length},
  totalSize: ${Object.values(docs).reduce((sum, content) => sum + content.length, 0)},
  categories: ${JSON.stringify([...new Set(Object.values(meta).map(m => m.category))])},
  generatedAt: '${new Date().toISOString()}'
};
`;
}

/**
 * Main function
 */
function main() {
  try {
    // Read documentation files
    const { docs, meta } = readDocs();

    if (Object.keys(docs).length === 0) {
      console.error('\n❌ No documentation files found!');
      process.exit(1);
    }

    // Calculate statistics
    const totalSize = Object.values(docs).reduce((sum, content) => sum + content.length, 0);
    const categories = [...new Set(Object.values(meta).map(m => m.category))];

    console.log('\n📊 Statistics:');
    console.log(`   Files: ${Object.keys(docs).length}`);
    console.log(`   Categories: ${categories.join(', ')}`);
    console.log(`   Total size: ${(totalSize / 1024).toFixed(2)} KB`);

    // Generate TypeScript module
    console.log('\n🔧 Generating TypeScript module...');
    const module = generateModule(docs, meta);

    // Ensure output directory exists
    const outputDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write to file
    fs.writeFileSync(OUTPUT_FILE, module, 'utf-8');

    const outputSize = (module.length / 1024).toFixed(2);
    console.log(`\n✅ Successfully generated: ${OUTPUT_FILE}`);
    console.log(`   Output size: ${outputSize} KB\n`);

    // Create .gitignore in generated directory
    const gitignorePath = path.join(outputDir, '.gitignore');
    if (!fs.existsSync(gitignorePath)) {
      fs.writeFileSync(gitignorePath, '# Auto-generated files\n*.ts\n*.js\n');
      console.log(`✓ Created ${gitignorePath}`);
    }

    console.log('🎉 Documentation generation complete!\n');
  } catch (error) {
    console.error('\n❌ Error generating documentation:');
    console.error(error);
    process.exit(1);
  }
}

// Run main function
main();
